'use strict';

var del = require('del');
var help = require('./helpers/help');

help.registerTask(
	'clean',
	'Removed all files and folders generated by the build',
	[],
	['clean']
);

module.exports = function createCleanTask(gulp, plugins, options, data) {
	gulp.task('clean', function cleanTask() {
		// skip clean unless clean flag provided, but always clean for clean command
		if (options.command !== 'clean' && options.noClean) {
			plugins.util.log('clean: disabled');
			return null;
		}

		plugins.util.log('clean: starting');
		return del(data.cleanPatterns).then(function delThen(paths) {
			if (paths.length) {
				plugins.util.log('clean: files/folders');
				paths.forEach(function pathsForEach(path) {
					plugins.util.log('clean: ' + path);
				});
			}
			plugins.util.log('clean: complete');
		});
	});
};
